'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("4fc5f082-3544-4d27-a8fb-41dde582f24e")> 

'Original file name:
'Generation date: 2/28/2011 2:00:17 PM
'''<summary>
'''There are no comments for testEntities in the schema.
'''</summary>
Partial Public Class testEntities
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new testEntities object using the connection string found in the 'testEntities' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=testEntities", "testEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new testEntities object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "testEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new testEntities object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "testEntities")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''There are no comments for Courses in the schema.
    '''</summary>
    Public ReadOnly Property Courses() As Global.System.Data.Objects.ObjectQuery(Of Courses)
        Get
            If (Me._Courses Is Nothing) Then
                Me._Courses = MyBase.CreateQuery(Of Courses)("[Courses]")
            End If
            Return Me._Courses
        End Get
    End Property
    Private _Courses As Global.System.Data.Objects.ObjectQuery(Of Courses)
    '''<summary>
    '''There are no comments for Courses in the schema.
    '''</summary>
    Public Sub AddToCourses(ByVal courses As Courses)
        MyBase.AddObject("Courses", courses)
    End Sub
End Class
'''<summary>
'''There are no comments for testModel.Courses in the schema.
'''</summary>
'''<KeyProperties>
'''CourseID
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="testModel", Name:="Courses"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Courses
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Courses object.
    '''</summary>
    '''<param name="courseID">Initial value of CourseID.</param>
    '''<param name="name">Initial value of Name.</param>
    '''<param name="credits">Initial value of Credits.</param>
    '''<param name="description">Initial value of Description.</param>
    Public Shared Function CreateCourses(ByVal courseID As Long, ByVal name As String, ByVal credits As Long, ByVal description As String) As Courses
        Dim courses As Courses = New Courses
        courses.CourseID = courseID
        courses.Name = name
        courses.Credits = credits
        courses.Description = description
        Return courses
    End Function
    '''<summary>
    '''There are no comments for Property CourseID in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property CourseID() As Long
        Get
            Return Me._CourseID
        End Get
        Set
            Me.OnCourseIDChanging(value)
            Me.ReportPropertyChanging("CourseID")
            Me._CourseID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("CourseID")
            Me.OnCourseIDChanged
        End Set
    End Property
    Private _CourseID As Long
    Partial Private Sub OnCourseIDChanging(ByVal value As Long)
        End Sub
    Partial Private Sub OnCourseIDChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Name in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Name() As String
        Get
            Return Me._Name
        End Get
        Set
            Me.OnNameChanging(value)
            Me.ReportPropertyChanging("Name")
            Me._Name = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Name")
            Me.OnNameChanged
        End Set
    End Property
    Private _Name As String
    Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNameChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Credits in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Credits() As Long
        Get
            Return Me._Credits
        End Get
        Set
            Me.OnCreditsChanging(value)
            Me.ReportPropertyChanging("Credits")
            Me._Credits = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Credits")
            Me.OnCreditsChanged
        End Set
    End Property
    Private _Credits As Long
    Partial Private Sub OnCreditsChanging(ByVal value As Long)
        End Sub
    Partial Private Sub OnCreditsChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Description in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Description() As String
        Get
            Return Me._Description
        End Get
        Set
            Me.OnDescriptionChanging(value)
            Me.ReportPropertyChanging("Description")
            Me._Description = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Description")
            Me.OnDescriptionChanged
        End Set
    End Property
    Private _Description As String
    Partial Private Sub OnDescriptionChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnDescriptionChanged()
        End Sub
End Class
